version: '3'
services:
 mitmproxy:
  image: mitmproxy/mitmproxy:latest
  volumes:
  - ~/.mitmproxy:/home/mitmproxy/.mitmproxy
  - ./:/home/mitmproxy
  command: mitmdump -s /home/mitmproxy/proxyscript.py

  ports:
  - 8080:8080

 my-service:
  build: .
  depends_on:
   - mitmproxy
  environment:
   MITMPROXY_URL: http://mitmproxy:8080
   CERT_PATH: /certs/.mitmproxy/mitmproxy-ca-cert.pem
  volumes:
  - ~/.mitmproxy:/certs/.mitmproxy


